// Sample dataset - In production, this would come from a database
// Format matches the requirements from the assignment
// Extended dataset with 110 transactions (11 pages at 10 items per page)

const sampleData = [
  {
    transactionId: "1234567",
    date: "2023-09-26",
    customerId: "CUST12016",
    customerName: "Neha Yadav",
    phoneNumber: "+91 9123456789",
    gender: "Female",
    age: 25,
    customerRegion: "South",
    customerType: "Regular",
    productId: "PROD0001",
    productName: "Summer Dress",
    brand: "StyleFlex",
    productCategory: "Clothing",
    tags: ["Fashion", "Women", "Summer"],
    quantity: 1,
    pricePerUnit: 1000,
    discountPercentage: 0,
    totalAmount: 1000,
    finalAmount: 1000,
    paymentMethod: "Card",
    orderStatus: "Completed",
    deliveryType: "Home Delivery",
    storeId: "STORE001",
    storeLocation: "Bangalore",
    salespersonId: "SP001",
    employeeName: "Harsh Agrawal"
  },
  {
    transactionId: "1234568",
    date: "2023-09-26",
    customerId: "CUST12016",
    customerName: "Neha Yadav",
    phoneNumber: "+91 9123456789",
    gender: "Female",
    age: 25,
    customerRegion: "South",
    customerType: "Premium",
    productId: "PROD0002",
    productName: "Casual Shirt",
    brand: "FitWear",
    productCategory: "Clothing",
    tags: ["Casual", "Men", "Office"],
    quantity: 2,
    pricePerUnit: 800,
    discountPercentage: 10,
    totalAmount: 1600,
    finalAmount: 1440,
    paymentMethod: "UPI",
    orderStatus: "Completed",
    deliveryType: "Store Pickup",
    storeId: "STORE001",
    storeLocation: "Bangalore",
    salespersonId: "SP002",
    employeeName: "Anurag Pratap Singh"
  },
  {
    transactionId: "1234569",
    date: "2023-09-25",
    customerId: "CUST12017",
    customerName: "Rajesh Kumar",
    phoneNumber: "+91 9876543210",
    gender: "Male",
    age: 35,
    customerRegion: "North",
    customerType: "Regular",
    productId: "PROD0003",
    productName: "Winter Jacket",
    brand: "WarmTech",
    productCategory: "Outerwear",
    tags: ["Winter", "Men", "Warm"],
    quantity: 1,
    pricePerUnit: 3500,
    discountPercentage: 15,
    totalAmount: 3500,
    finalAmount: 2975,
    paymentMethod: "Card",
    orderStatus: "Pending",
    deliveryType: "Home Delivery",
    storeId: "STORE002",
    storeLocation: "Delhi",
    salespersonId: "SP001",
    employeeName: "Harsh Agrawal"
  },
  {
    transactionId: "1234570",
    date: "2023-09-24",
    customerId: "CUST12018",
    customerName: "Priya Singh",
    phoneNumber: "+91 8765432109",
    gender: "Female",
    age: 28,
    customerRegion: "East",
    customerType: "Premium",
    productId: "PROD0004",
    productName: "Saree",
    brand: "EthnicWear",
    productCategory: "Traditional",
    tags: ["Ethnic", "Women", "Festival"],
    quantity: 1,
    pricePerUnit: 2500,
    discountPercentage: 20,
    totalAmount: 2500,
    finalAmount: 2000,
    paymentMethod: "EMI",
    orderStatus: "Completed",
    deliveryType: "Home Delivery",
    storeId: "STORE003",
    storeLocation: "Kolkata",
    salespersonId: "SP003",
    employeeName: "Sarah Thompson"
  },
  {
    transactionId: "1234571",
    date: "2023-09-23",
    customerId: "CUST12019",
    customerName: "Amit Patel",
    phoneNumber: "+91 7654321098",
    gender: "Male",
    age: 42,
    customerRegion: "West",
    customerType: "Regular",
    productId: "PROD0005",
    productName: "Formal Trousers",
    brand: "ClassicFit",
    productCategory: "Clothing",
    tags: ["Formal", "Men", "Office"],
    quantity: 3,
    pricePerUnit: 1200,
    discountPercentage: 5,
    totalAmount: 3600,
    finalAmount: 3420,
    paymentMethod: "Card",
    orderStatus: "Completed",
    deliveryType: "Store Pickup",
    storeId: "STORE004",
    storeLocation: "Mumbai",
    salespersonId: "SP004",
    employeeName: "Michael Brown"
  },
  {
    transactionId: "1234572",
    date: "2023-09-22",
    customerId: "CUST12020",
    customerName: "Anjali Verma",
    phoneNumber: "+91 6543210987",
    gender: "Female",
    age: 31,
    customerRegion: "South",
    customerType: "Premium",
    productId: "PROD0006",
    productName: "Handbag",
    brand: "LuxeStyle",
    productCategory: "Accessories",
    tags: ["Luxury", "Women", "Bags"],
    quantity: 1,
    pricePerUnit: 5000,
    discountPercentage: 25,
    totalAmount: 5000,
    finalAmount: 3750,
    paymentMethod: "Card",
    orderStatus: "Completed",
    deliveryType: "Home Delivery",
    storeId: "STORE001",
    storeLocation: "Bangalore",
    salespersonId: "SP002",
    employeeName: "Anurag Pratap Singh"
  },
  {
    transactionId: "1234573",
    date: "2023-09-21",
    customerId: "CUST12021",
    customerName: "Vikram Singh",
    phoneNumber: "+91 5432109876",
    gender: "Male",
    age: 29,
    customerRegion: "North",
    customerType: "Regular",
    productId: "PROD0007",
    productName: "Sneakers",
    brand: "SportWalk",
    productCategory: "Footwear",
    tags: ["Sports", "Men", "Casual"],
    quantity: 2,
    pricePerUnit: 3000,
    discountPercentage: 10,
    totalAmount: 6000,
    finalAmount: 5400,
    paymentMethod: "UPI",
    orderStatus: "Pending",
    deliveryType: "Home Delivery",
    storeId: "STORE002",
    storeLocation: "Delhi",
    salespersonId: "SP001",
    employeeName: "Harsh Agrawal"
  },
  {
    transactionId: "1234574",
    date: "2023-09-20",
    customerId: "CUST12022",
    customerName: "Divya Reddy",
    phoneNumber: "+91 4321098765",
    gender: "Female",
    age: 26,
    customerRegion: "East",
    customerType: "Regular",
    productId: "PROD0008",
    productName: "Sunglasses",
    brand: "VisionMax",
    productCategory: "Accessories",
    tags: ["Eyewear", "Unisex", "Summer"],
    quantity: 1,
    pricePerUnit: 2000,
    discountPercentage: 0,
    totalAmount: 2000,
    finalAmount: 2000,
    paymentMethod: "Card",
    orderStatus: "Completed",
    deliveryType: "Store Pickup",
    storeId: "STORE003",
    storeLocation: "Kolkata",
    salespersonId: "SP003",
    employeeName: "Sarah Thompson"
  },
  {
    transactionId: "1234575",
    date: "2023-09-19",
    customerId: "CUST12023",
    customerName: "Rohan Desai",
    phoneNumber: "+91 3210987654",
    gender: "Male",
    age: 33,
    customerRegion: "West",
    customerType: "Premium",
    productId: "PROD0009",
    productName: "Blazer",
    brand: "ElegantWear",
    productCategory: "Clothing",
    tags: ["Formal", "Men", "Party"],
    quantity: 1,
    pricePerUnit: 4500,
    discountPercentage: 30,
    totalAmount: 4500,
    finalAmount: 3150,
    paymentMethod: "Card",
    orderStatus: "Completed",
    deliveryType: "Home Delivery",
    storeId: "STORE004",
    storeLocation: "Mumbai",
    salespersonId: "SP004",
    employeeName: "Michael Brown"
  },
  {
    transactionId: "1234576",
    date: "2023-09-18",
    customerId: "CUST12024",
    customerName: "Kavya Nair",
    phoneNumber: "+91 2109876543",
    gender: "Female",
    age: 24,
    customerRegion: "South",
    customerType: "Regular",
    productId: "PROD0010",
    productName: "Lehenga",
    brand: "EthnicCharm",
    productCategory: "Traditional",
    tags: ["Ethnic", "Women", "Wedding"],
    quantity: 1,
    pricePerUnit: 8000,
    discountPercentage: 12,
    totalAmount: 8000,
    finalAmount: 7040,
    paymentMethod: "EMI",
    orderStatus: "Processing",
    deliveryType: "Home Delivery",
    storeId: "STORE001",
    storeLocation: "Bangalore",
    salespersonId: "SP002",
    employeeName: "Anurag Pratap Singh"
  },
  {
    transactionId: "1234577",
    date: "2023-09-17",
    customerId: "CUST12025",
    customerName: "Arjun Menon",
    phoneNumber: "+91 1098765432",
    gender: "Male",
    age: 27,
    customerRegion: "North",
    customerType: "Premium",
    productId: "PROD0011",
    productName: "Watch",
    brand: "TimeLux",
    productCategory: "Accessories",
    tags: ["Luxury", "Men", "Formal"],
    quantity: 1,
    pricePerUnit: 12000,
    discountPercentage: 35,
    totalAmount: 12000,
    finalAmount: 7800,
    paymentMethod: "Card",
    orderStatus: "Completed",
    deliveryType: "Store Pickup",
    storeId: "STORE002",
    storeLocation: "Delhi",
    salespersonId: "SP001",
    employeeName: "Harsh Agrawal"
  },
  { transactionId: "1234617", date: "2023-08-08", customerId: "CUST12065", customerName: "Aditya Singh", phoneNumber: "+91 6444444444", gender: "Male", age: 30, customerRegion: "South", customerType: "Regular", productId: "PROD0051", productName: "Cardigan", brand: "CozyKnit", productCategory: "Clothing", tags: ["Winter", "Women", "Warm"], quantity: 1, pricePerUnit: 2000, discountPercentage: 22, totalAmount: 2000, finalAmount: 1560, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE001", storeLocation: "Bangalore", salespersonId: "SP002", employeeName: "Anurag Pratap Singh" },
  { transactionId: "1234618", date: "2023-08-07", customerId: "CUST12066", customerName: "Ishita Verma", phoneNumber: "+91 6555555555", gender: "Female", age: 26, customerRegion: "North", customerType: "Premium", productId: "PROD0052", productName: "Turtleneck", brand: "ModernWear", productCategory: "Clothing", tags: ["Winter", "Women", "Casual"], quantity: 2, pricePerUnit: 1300, discountPercentage: 15, totalAmount: 2600, finalAmount: 2210, paymentMethod: "UPI", orderStatus: "Pending", deliveryType: "Home Delivery", storeId: "STORE002", storeLocation: "Delhi", salespersonId: "SP001", employeeName: "Harsh Agrawal" },
  { transactionId: "1234619", date: "2023-08-06", customerId: "CUST12067", customerName: "Yash Patel", phoneNumber: "+91 6666666666", gender: "Male", age: 34, customerRegion: "East", customerType: "Regular", productId: "PROD0053", productName: "Gym Shorts", brand: "FitGear", productCategory: "Clothing", tags: ["Sports", "Men", "Summer"], quantity: 3, pricePerUnit: 700, discountPercentage: 10, totalAmount: 2100, finalAmount: 1890, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Store Pickup", storeId: "STORE003", storeLocation: "Kolkata", salespersonId: "SP003", employeeName: "Sarah Thompson" },
  { transactionId: "1234620", date: "2023-08-05", customerId: "CUST12068", customerName: "Zara Khan", phoneNumber: "+91 6777777777", gender: "Female", age: 29, customerRegion: "West", customerType: "Premium", productId: "PROD0054", productName: "Bomber Jacket", brand: "UrbanStyle", productCategory: "Outerwear", tags: ["Casual", "Women", "Fashion"], quantity: 1, pricePerUnit: 3500, discountPercentage: 28, totalAmount: 3500, finalAmount: 2520, paymentMethod: "Card", orderStatus: "Processing", deliveryType: "Home Delivery", storeId: "STORE004", storeLocation: "Mumbai", salespersonId: "SP004", employeeName: "Michael Brown" },
  { transactionId: "1234621", date: "2023-08-04", customerId: "CUST12069", customerName: "Aryan Bhat", phoneNumber: "+91 6888888888", gender: "Male", age: 28, customerRegion: "South", customerType: "Regular", productId: "PROD0055", productName: "V-neck Sweater", brand: "ClassicWear", productCategory: "Clothing", tags: ["Casual", "Men", "Winter"], quantity: 1, pricePerUnit: 1800, discountPercentage: 12, totalAmount: 1800, finalAmount: 1584, paymentMethod: "UPI", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE001", storeLocation: "Bangalore", salespersonId: "SP002", employeeName: "Anurag Pratap Singh" },
  { transactionId: "1234622", date: "2023-08-03", customerId: "CUST12070", customerName: "Naina Gupta", phoneNumber: "+91 6999999999", gender: "Female", age: 32, customerRegion: "North", customerType: "Regular", productId: "PROD0056", productName: "Pencil Skirt", brand: "FormalWear", productCategory: "Clothing", tags: ["Formal", "Women", "Office"], quantity: 1, pricePerUnit: 1700, discountPercentage: 18, totalAmount: 1700, finalAmount: 1394, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE002", storeLocation: "Delhi", salespersonId: "SP001", employeeName: "Harsh Agrawal" },
  { transactionId: "1234623", date: "2023-08-02", customerId: "CUST12071", customerName: "Kabir Singh", phoneNumber: "+91 5111111111", gender: "Male", age: 36, customerRegion: "East", customerType: "Premium", productId: "PROD0057", productName: "Cargo Pants", brand: "UrbanGear", productCategory: "Clothing", tags: ["Casual", "Men", "Outdoor"], quantity: 1, pricePerUnit: 2200, discountPercentage: 20, totalAmount: 2200, finalAmount: 1760, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Store Pickup", storeId: "STORE003", storeLocation: "Kolkata", salespersonId: "SP003", employeeName: "Sarah Thompson" },
  { transactionId: "1234624", date: "2023-08-01", customerId: "CUST12072", customerName: "Priya Iyer", phoneNumber: "+91 5222222222", gender: "Female", age: 25, customerRegion: "West", customerType: "Regular", productId: "PROD0058", productName: "Floral Blouse", brand: "EthnicStyle", productCategory: "Clothing", tags: ["Fashion", "Women", "Ethnic"], quantity: 2, pricePerUnit: 950, discountPercentage: 25, totalAmount: 1900, finalAmount: 1425, paymentMethod: "UPI", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE004", storeLocation: "Mumbai", salespersonId: "SP004", employeeName: "Michael Brown" },
  { transactionId: "1234625", date: "2023-07-31", customerId: "CUST12073", customerName: "Ronak Mehta", phoneNumber: "+91 5333333333", gender: "Male", age: 39, customerRegion: "South", customerType: "Premium", productId: "PROD0059", productName: "Linen Pants", brand: "ComfortStyle", productCategory: "Clothing", tags: ["Casual", "Men", "Summer"], quantity: 2, pricePerUnit: 1600, discountPercentage: 8, totalAmount: 3200, finalAmount: 2944, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE001", storeLocation: "Bangalore", salespersonId: "SP002", employeeName: "Anurag Pratap Singh" },
  { transactionId: "1234626", date: "2023-07-30", customerId: "CUST12074", customerName: "Avni Kapoor", phoneNumber: "+91 5444444444", gender: "Female", age: 28, customerRegion: "North", customerType: "Regular", productId: "PROD0060", productName: "Sequin Top", brand: "PartyWear", productCategory: "Clothing", tags: ["Fashion", "Women", "Party"], quantity: 1, pricePerUnit: 1400, discountPercentage: 35, totalAmount: 1400, finalAmount: 910, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE002", storeLocation: "Delhi", salespersonId: "SP001", employeeName: "Harsh Agrawal" },
  { transactionId: "1234627", date: "2023-07-29", customerId: "CUST12075", customerName: "Harman Singh", phoneNumber: "+91 5555555555", gender: "Male", age: 31, customerRegion: "East", customerType: "Regular", productId: "PROD0061", productName: "Athleisure Wear", brand: "ActiveLife", productCategory: "Clothing", tags: ["Sports", "Unisex", "Casual"], quantity: 3, pricePerUnit: 800, discountPercentage: 11, totalAmount: 2400, finalAmount: 2136, paymentMethod: "UPI", orderStatus: "Pending", deliveryType: "Home Delivery", storeId: "STORE003", storeLocation: "Kolkata", salespersonId: "SP003", employeeName: "Sarah Thompson" },
  { transactionId: "1234628", date: "2023-07-28", customerId: "CUST12076", customerName: "Shruti Nair", phoneNumber: "+91 5666666666", gender: "Female", age: 27, customerRegion: "West", customerType: "Premium", productId: "PROD0062", productName: "Silk Dress", brand: "LuxuryStyle", productCategory: "Clothing", tags: ["Formal", "Women", "Luxury"], quantity: 1, pricePerUnit: 6000, discountPercentage: 32, totalAmount: 6000, finalAmount: 4080, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE004", storeLocation: "Mumbai", salespersonId: "SP004", employeeName: "Michael Brown" },
  { transactionId: "1234629", date: "2023-07-27", customerId: "CUST12077", customerName: "Vikram Chopra", phoneNumber: "+91 5777777777", gender: "Male", age: 35, customerRegion: "South", customerType: "Regular", productId: "PROD0063", productName: "Rugby Shirt", brand: "SportStyle", productCategory: "Clothing", tags: ["Sports", "Men", "Casual"], quantity: 2, pricePerUnit: 1100, discountPercentage: 7, totalAmount: 2200, finalAmount: 2046, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Store Pickup", storeId: "STORE001", storeLocation: "Bangalore", salespersonId: "SP002", employeeName: "Anurag Pratap Singh" },
  { transactionId: "1234630", date: "2023-07-26", customerId: "CUST12078", customerName: "Isha Deshmukh", phoneNumber: "+91 5888888888", gender: "Female", age: 24, customerRegion: "North", customerType: "Regular", productId: "PROD0064", productName: "Ruffled Blouse", brand: "TrendyStyle", productCategory: "Clothing", tags: ["Fashion", "Women", "Trendy"], quantity: 1, pricePerUnit: 1200, discountPercentage: 19, totalAmount: 1200, finalAmount: 972, paymentMethod: "UPI", orderStatus: "Processing", deliveryType: "Home Delivery", storeId: "STORE002", storeLocation: "Delhi", salespersonId: "SP001", employeeName: "Harsh Agrawal" },
  { transactionId: "1234631", date: "2023-07-25", customerId: "CUST12079", customerName: "Nitin Verma", phoneNumber: "+91 5999999999", gender: "Male", age: 40, customerRegion: "East", customerType: "Premium", productId: "PROD0065", productName: "Three-piece Suit", brand: "FormalClassic", productCategory: "Clothing", tags: ["Formal", "Men", "Office"], quantity: 1, pricePerUnit: 8500, discountPercentage: 40, totalAmount: 8500, finalAmount: 5100, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Store Pickup", storeId: "STORE003", storeLocation: "Kolkata", salespersonId: "SP003", employeeName: "Sarah Thompson" },
  { transactionId: "1234632", date: "2023-07-24", customerId: "CUST12080", customerName: "Anushka Roy", phoneNumber: "+91 4111111111", gender: "Female", age: 26, customerRegion: "West", customerType: "Regular", productId: "PROD0066", productName: "Denim Skirt", brand: "DenimStyle", productCategory: "Clothing", tags: ["Casual", "Women", "Denim"], quantity: 1, pricePerUnit: 1600, discountPercentage: 16, totalAmount: 1600, finalAmount: 1344, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE004", storeLocation: "Mumbai", salespersonId: "SP004", employeeName: "Michael Brown" },
  { transactionId: "1234633", date: "2023-07-23", customerId: "CUST12081", customerName: "Siddharth Jain", phoneNumber: "+91 4222222222", gender: "Male", age: 33, customerRegion: "South", customerType: "Premium", productId: "PROD0067", productName: "Slim Fit Shirt", brand: "ModernFit", productCategory: "Clothing", tags: ["Formal", "Men", "Office"], quantity: 3, pricePerUnit: 1400, discountPercentage: 14, totalAmount: 4200, finalAmount: 3612, paymentMethod: "UPI", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE001", storeLocation: "Bangalore", salespersonId: "SP002", employeeName: "Anurag Pratap Singh" },
  { transactionId: "1234634", date: "2023-07-22", customerId: "CUST12082", customerName: "Pallavi Sinha", phoneNumber: "+91 4333333333", gender: "Female", age: 30, customerRegion: "North", customerType: "Regular", productId: "PROD0068", productName: "Off-shoulder Top", brand: "FashionHub", productCategory: "Clothing", tags: ["Fashion", "Women", "Casual"], quantity: 1, pricePerUnit: 1100, discountPercentage: 20, totalAmount: 1100, finalAmount: 880, paymentMethod: "Card", orderStatus: "Pending", deliveryType: "Home Delivery", storeId: "STORE002", storeLocation: "Delhi", salespersonId: "SP001", employeeName: "Harsh Agrawal" },
  { transactionId: "1234635", date: "2023-07-21", customerId: "CUST12083", customerName: "Rohit Bhattacharya", phoneNumber: "+91 4444444444", gender: "Male", age: 37, customerRegion: "East", customerType: "Regular", productId: "PROD0069", productName: "Corduroy Pants", brand: "ClassicWear", productCategory: "Clothing", tags: ["Casual", "Men", "Office"], quantity: 1, pricePerUnit: 1900, discountPercentage: 9, totalAmount: 1900, finalAmount: 1729, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Store Pickup", storeId: "STORE003", storeLocation: "Kolkata", salespersonId: "SP003", employeeName: "Sarah Thompson" },
  { transactionId: "1234636", date: "2023-07-20", customerId: "CUST12084", customerName: "Megha Malhotra", phoneNumber: "+91 4555555555", gender: "Female", age: 29, customerRegion: "West", customerType: "Premium", productId: "PROD0070", productName: "Velvet Blazer", brand: "LuxeStyle", productCategory: "Outerwear", tags: ["Formal", "Women", "Luxury"], quantity: 1, pricePerUnit: 5500, discountPercentage: 30, totalAmount: 5500, finalAmount: 3850, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE004", storeLocation: "Mumbai", salespersonId: "SP004", employeeName: "Michael Brown" },
  { transactionId: "1234637", date: "2023-07-19", customerId: "CUST12085", customerName: "Gaurav Sharma", phoneNumber: "+91 4666666666", gender: "Male", age: 31, customerRegion: "South", customerType: "Regular", productId: "PROD0071", productName: "Striped T-shirt", brand: "CasualWear", productCategory: "Clothing", tags: ["Casual", "Men", "Everyday"], quantity: 2, pricePerUnit: 600, discountPercentage: 13, totalAmount: 1200, finalAmount: 1044, paymentMethod: "UPI", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE001", storeLocation: "Bangalore", salespersonId: "SP002", employeeName: "Anurag Pratap Singh" },
  { transactionId: "1234638", date: "2023-07-18", customerId: "CUST12086", customerName: "Seema Chakraborty", phoneNumber: "+91 4777777777", gender: "Female", age: 34, customerRegion: "North", customerType: "Regular", productId: "PROD0072", productName: "Ethnic Gown", brand: "EthnicCharm", productCategory: "Traditional", tags: ["Ethnic", "Women", "Festival"], quantity: 1, pricePerUnit: 3500, discountPercentage: 26, totalAmount: 3500, finalAmount: 2590, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE002", storeLocation: "Delhi", salespersonId: "SP001", employeeName: "Harsh Agrawal" },
  { transactionId: "1234639", date: "2023-07-17", customerId: "CUST12087", customerName: "Arjun Verma", phoneNumber: "+91 4888888888", gender: "Male", age: 28, customerRegion: "East", customerType: "Premium", productId: "PROD0073", productName: "Lace Top", brand: "ElegantWear", productCategory: "Clothing", tags: ["Fashion", "Women", "Elegant"], quantity: 1, pricePerUnit: 2200, discountPercentage: 29, totalAmount: 2200, finalAmount: 1562, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE003", storeLocation: "Kolkata", salespersonId: "SP003", employeeName: "Sarah Thompson" },
  { transactionId: "1234640", date: "2023-07-16", customerId: "CUST12088", customerName: "Diya Saxena", phoneNumber: "+91 4999999999", gender: "Female", age: 25, customerRegion: "West", customerType: "Regular", productId: "PROD0074", productName: "Jumpsuit", brand: "ModernStyle", productCategory: "Clothing", tags: ["Fashion", "Women", "Trendy"], quantity: 1, pricePerUnit: 2800, discountPercentage: 24, totalAmount: 2800, finalAmount: 2128, paymentMethod: "UPI", orderStatus: "Processing", deliveryType: "Home Delivery", storeId: "STORE004", storeLocation: "Mumbai", salespersonId: "SP004", employeeName: "Michael Brown" },
  { transactionId: "1234641", date: "2023-07-15", customerId: "CUST12089", customerName: "Rahul Bhat", phoneNumber: "+91 3111111111", gender: "Male", age: 32, customerRegion: "South", customerType: "Premium", productId: "PROD0075", productName: "Track Suit", brand: "SportStyle", productCategory: "Clothing", tags: ["Sports", "Men", "Active"], quantity: 1, pricePerUnit: 2500, discountPercentage: 17, totalAmount: 2500, finalAmount: 2075, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Store Pickup", storeId: "STORE001", storeLocation: "Bangalore", salespersonId: "SP002", employeeName: "Anurag Pratap Singh" },
  { transactionId: "1234642", date: "2023-07-14", customerId: "CUST12090", customerName: "Neha Fernandes", phoneNumber: "+91 3222222222", gender: "Female", age: 27, customerRegion: "North", customerType: "Regular", productId: "PROD0076", productName: "Midi Skirt", brand: "CasualStyle", productCategory: "Clothing", tags: ["Casual", "Women", "Summer"], quantity: 2, pricePerUnit: 1300, discountPercentage: 21, totalAmount: 2600, finalAmount: 2054, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE002", storeLocation: "Delhi", salespersonId: "SP001", employeeName: "Harsh Agrawal" },
  { transactionId: "1234643", date: "2023-07-13", customerId: "CUST12091", customerName: "Akshay Rao", phoneNumber: "+91 3333333333", gender: "Male", age: 36, customerRegion: "East", customerType: "Regular", productId: "PROD0077", productName: "Baseball Cap", brand: "Accessories", productCategory: "Accessories", tags: ["Sports", "Unisex", "Casual"], quantity: 3, pricePerUnit: 500, discountPercentage: 6, totalAmount: 1500, finalAmount: 1410, paymentMethod: "UPI", orderStatus: "Completed", deliveryType: "Store Pickup", storeId: "STORE003", storeLocation: "Kolkata", salespersonId: "SP003", employeeName: "Sarah Thompson" },
  { transactionId: "1234644", date: "2023-07-12", customerId: "CUST12092", customerName: "Riya Mishra", phoneNumber: "+91 3444444444", gender: "Female", age: 30, customerRegion: "West", customerType: "Premium", productId: "PROD0078", productName: "Leather Jacket", brand: "EdgeStyle", productCategory: "Outerwear", tags: ["Fashion", "Women", "Edgy"], quantity: 1, pricePerUnit: 7000, discountPercentage: 38, totalAmount: 7000, finalAmount: 4340, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE004", storeLocation: "Mumbai", salespersonId: "SP004", employeeName: "Michael Brown" },
  { transactionId: "1234645", date: "2023-07-11", customerId: "CUST12093", customerName: "Vaibhav Singh", phoneNumber: "+91 3555555555", gender: "Male", age: 29, customerRegion: "South", customerType: "Regular", productId: "PROD0079", productName: "Khaki Shorts", brand: "CasualGear", productCategory: "Clothing", tags: ["Casual", "Men", "Summer"], quantity: 1, pricePerUnit: 1200, discountPercentage: 1, totalAmount: 1200, finalAmount: 1188, paymentMethod: "Card", orderStatus: "Pending", deliveryType: "Home Delivery", storeId: "STORE001", storeLocation: "Bangalore", salespersonId: "SP002", employeeName: "Anurag Pratap Singh" },
  { transactionId: "1234646", date: "2023-07-10", customerId: "CUST12094", customerName: "Chitrangada Bhat", phoneNumber: "+91 3666666666", gender: "Female", age: 31, customerRegion: "North", customerType: "Regular", productId: "PROD0080", productName: "Shrug", brand: "LayerStyle", productCategory: "Outerwear", tags: ["Casual", "Women", "Layer"], quantity: 2, pricePerUnit: 800, discountPercentage: 23, totalAmount: 1600, finalAmount: 1232, paymentMethod: "UPI", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE002", storeLocation: "Delhi", salespersonId: "SP001", employeeName: "Harsh Agrawal" },
  { transactionId: "1234647", date: "2023-07-09", customerId: "CUST12095", customerName: "Manish Yadav", phoneNumber: "+91 3777777777", gender: "Male", age: 38, customerRegion: "East", customerType: "Premium", productId: "PROD0081", productName: "Golf Shirt", brand: "SportWear", productCategory: "Clothing", tags: ["Sports", "Men", "Casual"], quantity: 2, pricePerUnit: 1500, discountPercentage: 19, totalAmount: 3000, finalAmount: 2430, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE003", storeLocation: "Kolkata", salespersonId: "SP003", employeeName: "Sarah Thompson" },
  { transactionId: "1234648", date: "2023-07-08", customerId: "CUST12096", customerName: "Arpita Joshi", phoneNumber: "+91 3888888888", gender: "Female", age: 24, customerRegion: "West", customerType: "Regular", productId: "PROD0082", productName: "Tie Dye Top", brand: "TrendyStyle", productCategory: "Clothing", tags: ["Fashion", "Women", "Trendy"], quantity: 1, pricePerUnit: 1000, discountPercentage: 31, totalAmount: 1000, finalAmount: 690, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE004", storeLocation: "Mumbai", salespersonId: "SP004", employeeName: "Michael Brown" },
  { transactionId: "1234649", date: "2023-07-07", customerId: "CUST12097", customerName: "Sukhdev Kapoor", phoneNumber: "+91 3999999999", gender: "Male", age: 43, customerRegion: "South", customerType: "Regular", productId: "PROD0083", productName: "Linen Shirt", brand: "ComfortWear", productCategory: "Clothing", tags: ["Casual", "Men", "Summer"], quantity: 1, pricePerUnit: 1400, discountPercentage: 11, totalAmount: 1400, finalAmount: 1246, paymentMethod: "UPI", orderStatus: "Completed", deliveryType: "Store Pickup", storeId: "STORE001", storeLocation: "Bangalore", salespersonId: "SP002", employeeName: "Anurag Pratap Singh" },
  { transactionId: "1234650", date: "2023-07-06", customerId: "CUST12098", customerName: "Divya Pant", phoneNumber: "+91 2111111111", gender: "Female", age: 26, customerRegion: "North", customerType: "Premium", productId: "PROD0084", productName: "Strapless Dress", brand: "ElegantStyle", productCategory: "Clothing", tags: ["Fashion", "Women", "Party"], quantity: 1, pricePerUnit: 3200, discountPercentage: 27, totalAmount: 3200, finalAmount: 2336, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE002", storeLocation: "Delhi", salespersonId: "SP001", employeeName: "Harsh Agrawal" },
  { transactionId: "1234651", date: "2023-07-05", customerId: "CUST12099", customerName: "Pranav Thakur", phoneNumber: "+91 2222222222", gender: "Male", age: 34, customerRegion: "East", customerType: "Regular", productId: "PROD0085", productName: "Casual Blazer", brand: "SmartWear", productCategory: "Outerwear", tags: ["Casual", "Men", "Office"], quantity: 1, pricePerUnit: 3800, discountPercentage: 33, totalAmount: 3800, finalAmount: 2546, paymentMethod: "Card", orderStatus: "Processing", deliveryType: "Home Delivery", storeId: "STORE003", storeLocation: "Kolkata", salespersonId: "SP003", employeeName: "Sarah Thompson" },
  { transactionId: "1234652", date: "2023-07-04", customerId: "CUST12100", customerName: "Tina Walia", phoneNumber: "+91 2333333333", gender: "Female", age: 28, customerRegion: "West", customerType: "Regular", productId: "PROD0086", productName: "Wrap Top", brand: "FlexStyle", productCategory: "Clothing", tags: ["Casual", "Women", "Flexible"], quantity: 3, pricePerUnit: 700, discountPercentage: 15, totalAmount: 2100, finalAmount: 1785, paymentMethod: "UPI", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE004", storeLocation: "Mumbai", salespersonId: "SP004", employeeName: "Michael Brown" },
  { transactionId: "1234653", date: "2023-07-03", customerId: "CUST12101", customerName: "Vikrant Nair", phoneNumber: "+91 2444444444", gender: "Male", age: 37, customerRegion: "South", customerType: "Premium", productId: "PROD0087", productName: "Tweed Jacket", brand: "VintageStyle", productCategory: "Outerwear", tags: ["Formal", "Men", "Vintage"], quantity: 1, pricePerUnit: 6500, discountPercentage: 39, totalAmount: 6500, finalAmount: 3965, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Store Pickup", storeId: "STORE001", storeLocation: "Bangalore", salespersonId: "SP002", employeeName: "Anurag Pratap Singh" },
  { transactionId: "1234654", date: "2023-07-02", customerId: "CUST12102", customerName: "Aishwarya Roy", phoneNumber: "+91 2555555555", gender: "Female", age: 29, customerRegion: "North", customerType: "Regular", productId: "PROD0088", productName: "Linen Dress", brand: "SummerWear", productCategory: "Clothing", tags: ["Casual", "Women", "Summer"], quantity: 1, pricePerUnit: 2100, discountPercentage: 18, totalAmount: 2100, finalAmount: 1722, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE002", storeLocation: "Delhi", salespersonId: "SP001", employeeName: "Harsh Agrawal" },
  { transactionId: "1234655", date: "2023-07-01", customerId: "CUST12103", customerName: "Paramjeet Singh", phoneNumber: "+91 2666666666", gender: "Male", age: 40, customerRegion: "East", customerType: "Regular", productId: "PROD0089", productName: "Henley Long Sleeve", brand: "LayerWear", productCategory: "Clothing", tags: ["Casual", "Men", "Layer"], quantity: 2, pricePerUnit: 900, discountPercentage: 2, totalAmount: 1800, finalAmount: 1764, paymentMethod: "UPI", orderStatus: "Completed", deliveryType: "Store Pickup", storeId: "STORE003", storeLocation: "Kolkata", salespersonId: "SP003", employeeName: "Sarah Thompson" },
  { transactionId: "1234656", date: "2023-06-30", customerId: "CUST12104", customerName: "Jasmine Malik", phoneNumber: "+91 2777777777", gender: "Female", age: 32, customerRegion: "West", customerType: "Premium", productId: "PROD0090", productName: "Beaded Dress", brand: "LuxuryWear", productCategory: "Clothing", tags: ["Fashion", "Women", "Luxury"], quantity: 1, pricePerUnit: 8000, discountPercentage: 36, totalAmount: 8000, finalAmount: 5120, paymentMethod: "Card", orderStatus: "Completed", deliveryType: "Home Delivery", storeId: "STORE004", storeLocation: "Mumbai", salespersonId: "SP004", employeeName: "Michael Brown" }
];

export default sampleData;
